### ISSUE TITLE
fix formatting issues

### ISSUE THREAD

**Issue by fmalcher** [manfredsteyer/ddd-bk#3]
I collected a few points I couldn't change directly. There are comments in the PDF below.
If you have questions regarding my comments, let me know.

[enterprise-angular.pdf](https://github.com/manfredsteyer/ddd-bk/files/3764112/enterprise-angular.pdf)

**Comment by manfredsteyer** [comment]
Thanks a lot, Ferdinand. I'll release a new version with this and some PRs soon.

**Comment by manfredsteyer** [comment]
thx
